version: "3.8"

services:
  backend:
    build: ./backend
    container_name: chat-backend-container
    restart: always
    env_file:
      - ./backend/.env
    depends_on:
      - redis

    # Use the host's network directly
    network_mode: "host"

  # This is your new Redis service
  redis:
    image: redis:latest
    container_name: chat-redis-container
    restart: always
    # IMPORTANT: Set a strong password here for security
    command: redis-server --requirepass "Gta6free10"
